# highest priority first, lowest last 
tags   = ["cpp", "embedded", "embedded-linux", "aerospace", "arch", "robotics", "gui", "flutter", "backend", "go", "python", "math", "devops", "mgmt"]
lang   = "en"
output = "cpp-embedded.pdf"
