# highest priority first, lowest last 
tags = [
    "go",
    "backend",
    "arch",
    "devops",
    "refactoring",
    "cpp",
    "gui",
    "flutter",
    "python",
    "math",
]
lang = "en"
output = "default.pdf"
