// Package trackrepo implements usecase/track.Store over the host filesystem: it
// reads and writes one <id>.toml per application under <appdir>/applications/,
// owning all TOML (un)marshal and the local-date vs offset-datetime mapping
// (SPEC §3). The pure layers stay free of the serialization asymmetry: domain
// uses plain time.Time everywhere; this adapter maps day-granularity fields
// (applied_at, due, last_contact) to TOML local-date and event `at` to
// offset-datetime.
package trackrepo

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	toml "github.com/pelletier/go-toml/v2"

	"github.com/crispuscrew/resumegen/internal/domain"
	"github.com/crispuscrew/resumegen/internal/usecase/track"
)

const (
	subdir  = "applications"
	fileExt = ".toml"
	// Tracker entries hold PII (salary, contacts, notes): private by default.
	dirPerm  fs.FileMode = 0o700
	filePerm fs.FileMode = 0o600
)

// Store reads/writes applications under dir/applications/. dir is the resolved
// appdir root.
type Store struct {
	dir string
}

// New returns a track.Store rooted at appdir (its applications/ subdir is
// created lazily on the first Save).
func New(appdir string) track.Store { return Store{dir: appdir} }

func (s Store) appsDir() string { return filepath.Join(s.dir, subdir) }

// path maps an id to its file. IDs are generated by the slug (lowercase
// alphanumerics, '-', '_'), so anything with a path separator or a dot-dot is
// hostile input from the CLI (`apply show ../../x`) — refuse it instead of
// joining it into the filesystem.
func (s Store) path(id string) (string, error) {
	if id == "" || strings.ContainsAny(id, "/\\") || strings.Contains(id, "..") {
		return "", fmt.Errorf("invalid application id %q", id)
	}
	return filepath.Join(s.appsDir(), id+fileExt), nil
}

// Save marshals a to its <id>.toml, creating applications/ if needed. The
// write is atomic (temp file + rename in the same directory): a reader never
// observes a half-written file, and of two overlapping writers the last rename
// wins whole — this matters since v1.5, where the TUI runs Tracker calls in
// concurrent goroutines.
func (s Store) Save(_ context.Context, a domain.Application) error {
	if err := os.MkdirAll(s.appsDir(), dirPerm); err != nil {
		return fmt.Errorf("mkdir %s: %w", s.appsDir(), err)
	}
	raw, err := toml.Marshal(toWire(a))
	if err != nil {
		return fmt.Errorf("marshal application %s: %w", a.ID, err)
	}
	tmp, err := os.CreateTemp(s.appsDir(), a.ID+".tmp-*")
	if err != nil {
		return fmt.Errorf("temp for %s: %w", a.ID, err)
	}
	defer func() { _ = os.Remove(tmp.Name()) }() // no-op after a successful rename
	if _, err := tmp.Write(raw); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("write %s: %w", tmp.Name(), err)
	}
	if err := tmp.Chmod(filePerm); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("chmod %s: %w", tmp.Name(), err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close %s: %w", tmp.Name(), err)
	}
	dst, err := s.path(a.ID)
	if err != nil {
		return err
	}
	if err := os.Rename(tmp.Name(), dst); err != nil {
		return fmt.Errorf("rename to %s: %w", dst, err)
	}
	return nil
}

// Delete removes <id>.toml. A missing entry is an error, matching Load.
func (s Store) Delete(_ context.Context, id string) error {
	p, err := s.path(id)
	if err != nil {
		return err
	}
	if err := os.Remove(p); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("no application %q", id)
		}
		return fmt.Errorf("delete %s: %w", p, err)
	}
	return nil
}

// Load reads and decodes the application with the given id.
func (s Store) Load(_ context.Context, id string) (domain.Application, error) {
	p, perr := s.path(id)
	if perr != nil {
		return domain.Application{}, perr
	}
	raw, err := os.ReadFile(p)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return domain.Application{}, fmt.Errorf("no application %q", id)
		}
		return domain.Application{}, fmt.Errorf("read %s: %w", p, err)
	}
	return decode(raw)
}

// List reads every applications/*.toml entry, sorted by filename. A missing
// applications/ directory yields no entries (not an error).
func (s Store) List(_ context.Context) ([]domain.Application, error) {
	ents, err := os.ReadDir(s.appsDir())
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, nil
		}
		return nil, fmt.Errorf("read %s: %w", s.appsDir(), err)
	}
	names := make([]string, 0, len(ents))
	for _, e := range ents {
		if e.IsDir() || !strings.HasSuffix(e.Name(), fileExt) {
			continue
		}
		names = append(names, e.Name())
	}
	sort.Strings(names)
	out := make([]domain.Application, 0, len(names))
	for _, n := range names {
		raw, err := os.ReadFile(filepath.Join(s.appsDir(), n))
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", n, err)
		}
		a, err := decode(raw)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", n, err)
		}
		out = append(out, a)
	}
	return out, nil
}

// Exists reports whether <id>.toml is already present.
func (s Store) Exists(_ context.Context, id string) (bool, error) {
	p, perr := s.path(id)
	if perr != nil {
		return false, perr
	}
	_, err := os.Stat(p)
	if err == nil {
		return true, nil
	}
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	return false, fmt.Errorf("stat %s: %w", p, err)
}

// wire mirrors domain.Application but replaces day-granularity time.Time fields
// with toml.LocalDate so they serialize as date-only, while event `at` keeps
// full offset-datetime. This is the whole point of the adapter (SPEC §3).
type wire struct {
	ID          string         `toml:"id"`
	Company     string         `toml:"company"`
	Role        string         `toml:"role"`
	Source      string         `toml:"source"`
	Profile     string         `toml:"profile"`
	JDPath      string         `toml:"jd_path"`
	ResumePDF   string         `toml:"resume_pdf"`
	CoverLetter string         `toml:"cover_letter"`
	Status      string         `toml:"status"`
	SalaryRange string         `toml:"salary_range"`
	Remote      bool           `toml:"remote"`
	AppliedAt   toml.LocalDate `toml:"applied_at,omitempty"`
	Notes       string         `toml:"notes"`
	Contacts    []wireContact  `toml:"contacts"`
	Followups   []wireFollowup `toml:"followups"`
	Events      []wireEvent    `toml:"events"`
}

type wireEvent struct {
	At   time.Time `toml:"at"` // offset-datetime
	Kind string    `toml:"kind"`
	Note string    `toml:"note"`
}

type wireFollowup struct {
	// omitempty for the same reason as AppliedAt and LastContact: a zero
	// LocalDate serializes as 0000-00-00, which TOML cannot re-parse. A
	// hand-written followup that omits `due` loads fine, and without this the
	// next Save would rewrite it unparseable — destroying the entry and taking
	// `apply list` down for every application in the directory.
	Due    toml.LocalDate `toml:"due,omitempty"`
	Action string         `toml:"action"`
	Done   bool           `toml:"done"`
}

type wireContact struct {
	Name        string         `toml:"name"`
	Role        string         `toml:"role"`
	Channel     string         `toml:"channel"`
	LastContact toml.LocalDate `toml:"last_contact,omitempty"`
}

func toWire(a domain.Application) wire {
	w := wire{
		ID:          a.ID,
		Company:     a.Company,
		Role:        a.Role,
		Source:      a.Source,
		Profile:     a.Profile,
		JDPath:      a.JDPath,
		ResumePDF:   a.ResumePDF,
		CoverLetter: a.CoverLetter,
		Status:      string(a.Status),
		SalaryRange: a.SalaryRange,
		Remote:      a.Remote,
		AppliedAt:   toLocalDate(a.AppliedAt),
		Notes:       a.Notes,
	}
	for _, c := range a.Contacts {
		w.Contacts = append(w.Contacts, wireContact{
			Name: c.Name, Role: c.Role, Channel: c.Channel,
			LastContact: toLocalDate(c.LastContact),
		})
	}
	for _, f := range a.Followups {
		w.Followups = append(w.Followups, wireFollowup{
			Due: toLocalDate(f.Due), Action: f.Action, Done: f.Done,
		})
	}
	for _, e := range a.Events {
		w.Events = append(w.Events, wireEvent{At: e.At, Kind: e.Kind, Note: e.Note})
	}
	return w
}

func fromWire(w wire) domain.Application {
	a := domain.Application{
		ID:          w.ID,
		Company:     w.Company,
		Role:        w.Role,
		Source:      w.Source,
		Profile:     w.Profile,
		JDPath:      w.JDPath,
		ResumePDF:   w.ResumePDF,
		CoverLetter: w.CoverLetter,
		Status:      domain.Status(w.Status),
		SalaryRange: w.SalaryRange,
		Remote:      w.Remote,
		AppliedAt:   fromLocalDate(w.AppliedAt),
		Notes:       w.Notes,
	}
	for _, c := range w.Contacts {
		a.Contacts = append(a.Contacts, domain.AppContact{
			Name: c.Name, Role: c.Role, Channel: c.Channel,
			LastContact: fromLocalDate(c.LastContact),
		})
	}
	for _, f := range w.Followups {
		a.Followups = append(a.Followups, domain.Followup{
			Due: fromLocalDate(f.Due), Action: f.Action, Done: f.Done,
		})
	}
	for _, e := range w.Events {
		a.Events = append(a.Events, domain.Event{At: e.At, Kind: e.Kind, Note: e.Note})
	}
	return a
}

func decode(raw []byte) (domain.Application, error) {
	var w wire
	if err := toml.Unmarshal(raw, &w); err != nil {
		return domain.Application{}, fmt.Errorf("parse application: %w", err)
	}
	return fromWire(w), nil
}

// toLocalDate projects a time.Time onto its calendar day. A zero time maps to a
// zero LocalDate, which go-toml omits.
func toLocalDate(t time.Time) toml.LocalDate {
	if t.IsZero() {
		return toml.LocalDate{}
	}
	u := t.UTC()
	return toml.LocalDate{Year: u.Year(), Month: int(u.Month()), Day: u.Day()}
}

// Zero times rely on `omitempty` on the wire fields: a never-applied entry's
// applied_at is simply ABSENT from the file (a zero LocalDate would serialize
// as "0000-00-00", which TOML cannot re-parse).

// fromLocalDate lifts a LocalDate back to time.Time at UTC midnight (SPEC §3).
// A zero LocalDate stays a zero time.Time.
func fromLocalDate(d toml.LocalDate) time.Time {
	if d.Year == 0 && d.Month == 0 && d.Day == 0 {
		return time.Time{}
	}
	return d.AsTime(time.UTC)
}
